"use client"

import { createContext, useContext, useState, useCallback, type ReactNode } from "react"

interface Property {
  id: number
  propertyId: number
  roomNumber: string
  projectId: number
  projectName: string
  location: string[]
  status: string
  bedRoom: number
  bathRoom: number
  roomSize: number
  rentalRate: number
  sell: number
  roomType: string
  phone: string
  lineId: string
  indexFbUrl: string
  imageUrls: string[]
  isPetFriendly: boolean
  isOwner: boolean
  distanceToStation: number
  distanceStation: string
  note: string
  carPark: number
  messageToPost: string
  roomAmenities: string[]
  floor: number
  whenAvailable: string
  isAcceptShortTerm: boolean
  propertyCode: string
  projectPropertyCode: string
}

interface Project {
  id: number
  projectName: string
  projectCode: string
  projectLocation: string[]
  projectImageUrl: string[]
  projectFacilities: string[]
  addressNumber: string
  addressSubDistrict: string
  addressDistrict: string
  addressProvince: string
  addressZipcode: string
}

interface SearchParams {
  search: string
  roomType: string
  bedRoom: string
  minSize: string
  maxSize: string
  minPrice: string
  maxPrice: string
}

interface PropertyContextType {
  properties: Property[]
  projects: Project[]
  propertyTypes: string[]
  stations: string[]
  roomAmenitiesOptions: string[]
  whenAvailableOptions: string[]
  loading: boolean
  saving: boolean
  error: string | null
  successMessage: string | null
  fetchProperties: (
    page: number,
    limit: number,
    params: SearchParams,
  ) => Promise<{
    success: boolean
    total: number
    page: number
    totalPages: number
  }>
  getProperty: (id: number) => Promise<{ success: boolean; data?: Property }>
  updateProperty: (id: number, data: Partial<Property>) => Promise<{ success: boolean; message?: string }>
  clearError: () => void
  clearSuccessMessage: () => void
}

const PropertyContext = createContext<PropertyContextType | undefined>(undefined)

// Mock data
const mockProjects: Project[] = [
  {
    id: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    projectCode: "LSP001",
    projectLocation: ["Phetchaburi", "Makkasan", "Bangkok"],
    projectImageUrl: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    projectFacilities: ["Swimming Pool", "Fitness Center", "24/7 Security", "Parking"],
    addressNumber: "123",
    addressSubDistrict: "Makkasan",
    addressDistrict: "Ratchathewi",
    addressProvince: "Bangkok",
    addressZipcode: "10400",
  },
  {
    id: 2,
    projectName: "The Base Park East Sukhumvit 77",
    projectCode: "BPE002",
    projectLocation: ["Sukhumvit", "On Nut", "Bangkok"],
    projectImageUrl: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    projectFacilities: ["Swimming Pool", "Gym", "Garden", "Security"],
    addressNumber: "456",
    addressSubDistrict: "On Nut",
    addressDistrict: "Suan Luang",
    addressProvince: "Bangkok",
    addressZipcode: "10250",
  },
  {
    id: 3,
    projectName: "Noble Ploenchit",
    projectCode: "NPL003",
    projectLocation: ["Ploenchit", "Wireless Road", "Bangkok"],
    projectImageUrl: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    projectFacilities: ["Infinity Pool", "Sky Gym", "Concierge", "Valet Parking"],
    addressNumber: "789",
    addressSubDistrict: "Lumphini",
    addressDistrict: "Pathum Wan",
    addressProvince: "Bangkok",
    addressZipcode: "10330",
  },
]

const mockProperties: Property[] = [
  {
    id: 1,
    propertyId: 1001,
    roomNumber: "A-1205",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 35,
    rentalRate: 18000,
    sell: 3500000,
    roomType: "Condo",
    phone: "081-234-5678",
    lineId: "@property123",
    indexFbUrl: "https://facebook.com/property123",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 200,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Fully furnished, ready to move in",
    carPark: 1,
    messageToPost: "Beautiful 1BR condo near Airport Rail Link, fully furnished, pet-friendly!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV"],
    floor: 12,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P001-A1205",
    projectPropertyCode: "LSP001-A1205",
  },
  {
    id: 2,
    propertyId: 1002,
    roomNumber: "B-0815",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 45,
    rentalRate: 25000,
    sell: 4200000,
    roomType: "Condo",
    phone: "082-345-6789",
    lineId: "@property456",
    indexFbUrl: "https://facebook.com/property456",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 150,
    distanceStation: "On Nut BTS",
    note: "Corner unit with great city view",
    carPark: 1,
    messageToPost: "Spacious 2BR corner unit with city view, near BTS On Nut!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony"],
    floor: 8,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P002-B0815",
    projectPropertyCode: "BPE002-B0815",
  },
  {
    id: 3,
    propertyId: 1003,
    roomNumber: "C-2010",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "rented",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 85,
    rentalRate: 65000,
    sell: 12000000,
    roomType: "Condo",
    phone: "083-456-7890",
    lineId: "@property789",
    indexFbUrl: "https://facebook.com/property789",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 100,
    distanceStation: "Ploenchit BTS",
    note: "Luxury penthouse with panoramic city views",
    carPark: 2,
    messageToPost: "Luxury 3BR penthouse in prime location, stunning city views!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Bathtub", "Walk-in Closet"],
    floor: 20,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P003-C2010",
    projectPropertyCode: "NPL003-C2010",
  },
  // 50 Additional Properties
  {
    id: 4,
    propertyId: 1004,
    roomNumber: "A-0501",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 32,
    rentalRate: 16500,
    sell: 3200000,
    roomType: "Condo",
    phone: "084-111-2222",
    lineId: "@prop004",
    indexFbUrl: "https://facebook.com/prop004",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 180,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Cozy studio with modern amenities",
    carPark: 0,
    messageToPost: "Affordable 1BR condo near Airport Rail Link!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi"],
    floor: 5,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P004-A0501",
    projectPropertyCode: "LSP001-A0501",
  },
  {
    id: 5,
    propertyId: 1005,
    roomNumber: "B-1203",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 48,
    rentalRate: 27000,
    sell: 4500000,
    roomType: "Condo",
    phone: "085-222-3333",
    lineId: "@prop005",
    indexFbUrl: "https://facebook.com/prop005",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 120,
    distanceStation: "On Nut BTS",
    note: "High floor with pool view",
    carPark: 1,
    messageToPost: "2BR with pool view, pet-friendly!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Bathtub"],
    floor: 12,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P005-B1203",
    projectPropertyCode: "BPE002-B1203",
  },
  {
    id: 6,
    propertyId: 1006,
    roomNumber: "C-1505",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 65,
    rentalRate: 55000,
    sell: 9500000,
    roomType: "Condo",
    phone: "086-333-4444",
    lineId: "@prop006",
    indexFbUrl: "https://facebook.com/prop006",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 80,
    distanceStation: "Ploenchit BTS",
    note: "Premium location with city views",
    carPark: 1,
    messageToPost: "Premium 2BR in Noble Ploenchit!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Walk-in Closet"],
    floor: 15,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P006-C1505",
    projectPropertyCode: "NPL003-C1505",
  },
  {
    id: 7,
    propertyId: 1007,
    roomNumber: "A-0802",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 38,
    rentalRate: 19000,
    sell: 3800000,
    roomType: "Condo",
    phone: "087-444-5555",
    lineId: "@prop007",
    indexFbUrl: "https://facebook.com/prop007",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 220,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Recently renovated with new furniture",
    carPark: 1,
    messageToPost: "Renovated 1BR with new furniture!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Microwave"],
    floor: 8,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: true,
    propertyCode: "P007-A0802",
    projectPropertyCode: "LSP001-A0802",
  },
  {
    id: 8,
    propertyId: 1008,
    roomNumber: "D-0301",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 35,
    rentalRate: 22000,
    sell: 3800000,
    roomType: "Condo",
    phone: "088-555-6666",
    lineId: "@prop008",
    indexFbUrl: "https://facebook.com/prop008",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 160,
    distanceStation: "On Nut BTS",
    note: "Ground floor with garden access",
    carPark: 0,
    messageToPost: "1BR with garden access!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen"],
    floor: 3,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P008-D0301",
    projectPropertyCode: "BPE002-D0301",
  },
  {
    id: 9,
    propertyId: 1009,
    roomNumber: "E-2201",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "sold",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 95,
    rentalRate: 75000,
    sell: 15000000,
    roomType: "Condo",
    phone: "089-666-7777",
    lineId: "@prop009",
    indexFbUrl: "https://facebook.com/prop009",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 90,
    distanceStation: "Ploenchit BTS",
    note: "Duplex penthouse with private terrace",
    carPark: 2,
    messageToPost: "Luxury duplex penthouse with terrace!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Bathtub",
      "Walk-in Closet",
      "Built-in Wardrobe",
    ],
    floor: 22,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: false,
    propertyCode: "P009-E2201",
    projectPropertyCode: "NPL003-E2201",
  },
  {
    id: 10,
    propertyId: 1010,
    roomNumber: "F-0701",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 55,
    rentalRate: 28000,
    sell: 5200000,
    roomType: "Condo",
    phone: "090-777-8888",
    lineId: "@prop010",
    indexFbUrl: "https://facebook.com/prop010",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 190,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Spacious 2BR with separate dining area",
    carPark: 1,
    messageToPost: "Spacious 2BR with dining area, pet-friendly!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Kitchen"],
    floor: 7,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P010-F0701",
    projectPropertyCode: "LSP001-F0701",
  },
  // Continue with properties 11-53...
  {
    id: 11,
    propertyId: 1011,
    roomNumber: "G-1401",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 2,
    roomSize: 72,
    rentalRate: 42000,
    sell: 7200000,
    roomType: "Condo",
    phone: "091-888-9999",
    lineId: "@prop011",
    indexFbUrl: "https://facebook.com/prop011",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 140,
    distanceStation: "On Nut BTS",
    note: "Family-friendly 3BR with study room",
    carPark: 2,
    messageToPost: "Family 3BR with study room!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen", "Study Room"],
    floor: 14,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P011-G1401",
    projectPropertyCode: "BPE002-G1401",
  },
  {
    id: 12,
    propertyId: 1012,
    roomNumber: "H-0901",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 42,
    rentalRate: 38000,
    sell: 6800000,
    roomType: "Condo",
    phone: "092-999-0000",
    lineId: "@prop012",
    indexFbUrl: "https://facebook.com/prop012",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 70,
    distanceStation: "Ploenchit BTS",
    note: "Compact luxury studio in prime location",
    carPark: 0,
    messageToPost: "Luxury studio in prime Ploenchit!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen"],
    floor: 9,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P012-H0901",
    projectPropertyCode: "NPL003-H0901",
  },
  {
    id: 13,
    propertyId: 1013,
    roomNumber: "A-1801",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 36,
    rentalRate: 17500,
    sell: 3400000,
    roomType: "Condo",
    phone: "093-000-1111",
    lineId: "@prop013",
    indexFbUrl: "https://facebook.com/prop013",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 210,
    distanceStation: "Makkasan Airport Rail Link",
    note: "High floor with city skyline view",
    carPark: 1,
    messageToPost: "High floor 1BR with skyline view!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "TV"],
    floor: 18,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P013-A1801",
    projectPropertyCode: "LSP001-A1801",
  },
  {
    id: 14,
    propertyId: 1014,
    roomNumber: "B-0602",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 1,
    roomSize: 50,
    rentalRate: 26500,
    sell: 4300000,
    roomType: "Apartment",
    phone: "094-111-2222",
    lineId: "@prop014",
    indexFbUrl: "https://facebook.com/prop014",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 170,
    distanceStation: "On Nut BTS",
    note: "Affordable 2BR apartment with balcony",
    carPark: 1,
    messageToPost: "Affordable 2BR apartment with balcony!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Balcony"],
    floor: 6,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P014-B0602",
    projectPropertyCode: "BPE002-B0602",
  },
  {
    id: 15,
    propertyId: 1015,
    roomNumber: "C-1102",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 68,
    rentalRate: 58000,
    sell: 10200000,
    roomType: "Condo",
    phone: "095-222-3333",
    lineId: "@prop015",
    indexFbUrl: "https://facebook.com/prop015",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 85,
    distanceStation: "Ploenchit BTS",
    note: "Modern 2BR with marble bathroom",
    carPark: 1,
    messageToPost: "Modern 2BR with marble bathroom!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Marble Bathroom"],
    floor: 11,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P015-C1102",
    projectPropertyCode: "NPL003-C1102",
  },
  // Properties 16-25
  {
    id: 16,
    propertyId: 1016,
    roomNumber: "D-2005",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 2,
    roomSize: 78,
    rentalRate: 35000,
    sell: 6500000,
    roomType: "Condo",
    phone: "096-333-4444",
    lineId: "@prop016",
    indexFbUrl: "https://facebook.com/prop016",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 200,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Penthouse level with private access",
    carPark: 2,
    messageToPost: "Penthouse 3BR with private access!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Kitchen", "Balcony"],
    floor: 20,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P016-D2005",
    projectPropertyCode: "LSP001-D2005",
  },
  {
    id: 17,
    propertyId: 1017,
    roomNumber: "E-0403",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 33,
    rentalRate: 21000,
    sell: 3600000,
    roomType: "Condo",
    phone: "097-444-5555",
    lineId: "@prop017",
    indexFbUrl: "https://facebook.com/prop017",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 155,
    distanceStation: "On Nut BTS",
    note: "Cozy studio perfect for singles",
    carPark: 0,
    messageToPost: "Cozy studio perfect for singles!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi"],
    floor: 4,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: true,
    propertyCode: "P017-E0403",
    projectPropertyCode: "BPE002-E0403",
  },
  {
    id: 18,
    propertyId: 1018,
    roomNumber: "F-1605",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 105,
    rentalRate: 85000,
    sell: 18000000,
    roomType: "Condo",
    phone: "098-555-6666",
    lineId: "@prop018",
    indexFbUrl: "https://facebook.com/prop018",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 75,
    distanceStation: "Ploenchit BTS",
    note: "Ultra-luxury 3BR with panoramic views",
    carPark: 2,
    messageToPost: "Ultra-luxury 3BR with panoramic views!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Bathtub",
      "Walk-in Closet",
      "Built-in Wardrobe",
      "Kitchen",
    ],
    floor: 16,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P018-F1605",
    projectPropertyCode: "NPL003-F1605",
  },
  {
    id: 19,
    propertyId: 1019,
    roomNumber: "G-0804",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 40,
    rentalRate: 20000,
    sell: 4000000,
    roomType: "Condo",
    phone: "099-666-7777",
    lineId: "@prop019",
    indexFbUrl: "https://facebook.com/prop019",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 185,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Corner unit with extra windows",
    carPark: 1,
    messageToPost: "Corner 1BR with extra natural light!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV"],
    floor: 8,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P019-G0804",
    projectPropertyCode: "LSP001-G0804",
  },
  {
    id: 20,
    propertyId: 1020,
    roomNumber: "H-1207",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 52,
    rentalRate: 29000,
    sell: 4800000,
    roomType: "Condo",
    phone: "080-777-8888",
    lineId: "@prop020",
    indexFbUrl: "https://facebook.com/prop020",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 130,
    distanceStation: "On Nut BTS",
    note: "Mid-floor 2BR with garden view",
    carPark: 1,
    messageToPost: "2BR with beautiful garden view!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen"],
    floor: 12,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P020-H1207",
    projectPropertyCode: "BPE002-H1207",
  },
  // Properties 21-30
  {
    id: 21,
    propertyId: 1021,
    roomNumber: "A-0305",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "sold",
    bedRoom: 2,
    bathRoom: 1,
    roomSize: 58,
    rentalRate: 24000,
    sell: 4600000,
    roomType: "Apartment",
    phone: "081-888-9999",
    lineId: "@prop021",
    indexFbUrl: "https://facebook.com/prop021",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 195,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Ground level with easy access",
    carPark: 1,
    messageToPost: "Ground level 2BR with easy access!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen"],
    floor: 3,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: false,
    propertyCode: "P021-A0305",
    projectPropertyCode: "LSP001-A0305",
  },
  {
    id: 22,
    propertyId: 1022,
    roomNumber: "B-1508",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 2,
    roomSize: 75,
    rentalRate: 45000,
    sell: 7800000,
    roomType: "Condo",
    phone: "082-999-0000",
    lineId: "@prop022",
    indexFbUrl: "https://facebook.com/prop022",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 145,
    distanceStation: "On Nut BTS",
    note: "Spacious family unit with maid's room",
    carPark: 2,
    messageToPost: "Spacious 3BR family unit with maid's room!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen", "Maid's Room"],
    floor: 15,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P022-B1508",
    projectPropertyCode: "BPE002-B1508",
  },
  {
    id: 23,
    propertyId: 1023,
    roomNumber: "C-0702",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 45,
    rentalRate: 42000,
    sell: 7500000,
    roomType: "Condo",
    phone: "083-000-1111",
    lineId: "@prop023",
    indexFbUrl: "https://facebook.com/prop023",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 95,
    distanceStation: "Ploenchit BTS",
    note: "Luxury studio with separate bedroom area",
    carPark: 0,
    messageToPost: "Luxury studio with separate bedroom!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen", "Built-in Wardrobe"],
    floor: 7,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P023-C0702",
    projectPropertyCode: "NPL003-C0702",
  },
  {
    id: 24,
    propertyId: 1024,
    roomNumber: "D-1903",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "rented",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 62,
    rentalRate: 32000,
    sell: 5800000,
    roomType: "Condo",
    phone: "084-111-2222",
    lineId: "@prop024",
    indexFbUrl: "https://facebook.com/prop024",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 175,
    distanceStation: "Makkasan Airport Rail Link",
    note: "High floor 2BR with city and river views",
    carPark: 1,
    messageToPost: "High floor 2BR with city and river views!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Balcony"],
    floor: 19,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P024-D1903",
    projectPropertyCode: "LSP001-D1903",
  },
  {
    id: 25,
    propertyId: 1025,
    roomNumber: "E-0506",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 38,
    rentalRate: 23500,
    sell: 4100000,
    roomType: "Condo",
    phone: "085-222-3333",
    lineId: "@prop025",
    indexFbUrl: "https://facebook.com/prop025",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 165,
    distanceStation: "On Nut BTS",
    note: "Compact 1BR with efficient layout",
    carPark: 0,
    messageToPost: "Compact 1BR with efficient layout!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Microwave"],
    floor: 5,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P025-E0506",
    projectPropertyCode: "BPE002-E0506",
  },
  // Properties 26-35
  {
    id: 26,
    propertyId: 1026,
    roomNumber: "F-1304",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 72,
    rentalRate: 62000,
    sell: 11500000,
    roomType: "Condo",
    phone: "086-333-4444",
    lineId: "@prop026",
    indexFbUrl: "https://facebook.com/prop026",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 88,
    distanceStation: "Ploenchit BTS",
    note: "Premium 2BR with hardwood floors",
    carPark: 1,
    messageToPost: "Premium 2BR with hardwood floors!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Hardwood Floors",
      "Walk-in Closet",
    ],
    floor: 13,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P026-F1304",
    projectPropertyCode: "NPL003-F1304",
  },
  {
    id: 27,
    propertyId: 1027,
    roomNumber: "G-0607",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 34,
    rentalRate: 16000,
    sell: 3100000,
    roomType: "Condo",
    phone: "087-444-5555",
    lineId: "@prop027",
    indexFbUrl: "https://facebook.com/prop027",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 205,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Budget-friendly studio with balcony",
    carPark: 0,
    messageToPost: "Budget-friendly studio with balcony!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Balcony"],
    floor: 6,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P027-G0607",
    projectPropertyCode: "LSP001-G0607",
  },
  {
    id: 28,
    propertyId: 1028,
    roomNumber: "H-1709",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "rented",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 56,
    rentalRate: 31000,
    sell: 5200000,
    roomType: "Condo",
    phone: "088-555-6666",
    lineId: "@prop028",
    indexFbUrl: "https://facebook.com/prop028",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 135,
    distanceStation: "On Nut BTS",
    note: "High floor 2BR with pool and city views",
    carPark: 1,
    messageToPost: "High floor 2BR with pool and city views!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Bathtub"],
    floor: 17,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: false,
    propertyCode: "P028-H1709",
    projectPropertyCode: "BPE002-H1709",
  },
  {
    id: 29,
    propertyId: 1029,
    roomNumber: "A-2108",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 110,
    rentalRate: 95000,
    sell: 20000000,
    roomType: "Condo",
    phone: "089-666-7777",
    lineId: "@prop029",
    indexFbUrl: "https://facebook.com/prop029",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 65,
    distanceStation: "Ploenchit BTS",
    note: "Penthouse level with private elevator",
    carPark: 3,
    messageToPost: "Penthouse with private elevator access!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Bathtub",
      "Walk-in Closet",
      "Built-in Wardrobe",
      "Kitchen",
      "Study Room",
    ],
    floor: 21,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P029-A2108",
    projectPropertyCode: "NPL003-A2108",
  },
  {
    id: 30,
    propertyId: 1030,
    roomNumber: "B-1005",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 1,
    roomSize: 48,
    rentalRate: 22000,
    sell: 4200000,
    roomType: "Apartment",
    phone: "090-777-8888",
    lineId: "@prop030",
    indexFbUrl: "https://facebook.com/prop030",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 190,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Affordable 2BR apartment for families",
    carPark: 1,
    messageToPost: "Affordable 2BR apartment for families!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen"],
    floor: 10,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P030-B1005",
    projectPropertyCode: "LSP001-B1005",
  },
  // Properties 31-40
  {
    id: 31,
    propertyId: 1031,
    roomNumber: "C-0408",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 36,
    rentalRate: 22500,
    sell: 3900000,
    roomType: "Condo",
    phone: "091-888-9999",
    lineId: "@prop031",
    indexFbUrl: "https://facebook.com/prop031",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 150,
    distanceStation: "On Nut BTS",
    note: "Modern 1BR with smart home features",
    carPark: 0,
    messageToPost: "Modern 1BR with smart home features!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "TV"],
    floor: 4,
    whenAvailable: "Next month",
    isAcceptShortTerm: true,
    propertyCode: "P031-C0408",
    projectPropertyCode: "BPE002-C0408",
  },
  {
    id: 32,
    propertyId: 1032,
    roomNumber: "D-1406",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "sold",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 75,
    rentalRate: 68000,
    sell: 13500000,
    roomType: "Condo",
    phone: "092-999-0000",
    lineId: "@prop032",
    indexFbUrl: "https://facebook.com/prop032",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 78,
    distanceStation: "Ploenchit BTS",
    note: "Luxury 2BR with floor-to-ceiling windows",
    carPark: 1,
    messageToPost: "Luxury 2BR with floor-to-ceiling windows!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Floor-to-Ceiling Windows",
      "Marble Bathroom",
    ],
    floor: 14,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: false,
    propertyCode: "P032-D1406",
    projectPropertyCode: "NPL003-D1406",
  },
  {
    id: 33,
    propertyId: 1033,
    roomNumber: "E-0709",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 41,
    rentalRate: 21000,
    sell: 4200000,
    roomType: "Condo",
    phone: "093-000-1111",
    lineId: "@prop033",
    indexFbUrl: "https://facebook.com/prop033",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 180,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Spacious 1BR with separate living area",
    carPark: 1,
    messageToPost: "Spacious 1BR with separate living area!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Living Room"],
    floor: 7,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P033-E0709",
    projectPropertyCode: "LSP001-E0709",
  },
  {
    id: 34,
    propertyId: 1034,
    roomNumber: "F-1810",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 3,
    bathRoom: 2,
    roomSize: 80,
    rentalRate: 48000,
    sell: 8500000,
    roomType: "Condo",
    phone: "094-111-2222",
    lineId: "@prop034",
    indexFbUrl: "https://facebook.com/prop034",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 125,
    distanceStation: "On Nut BTS",
    note: "Corner 3BR unit with panoramic views",
    carPark: 2,
    messageToPost: "Corner 3BR with panoramic views!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen", "Storage Room"],
    floor: 18,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P034-F1810",
    projectPropertyCode: "BPE002-F1810",
  },
  {
    id: 35,
    propertyId: 1035,
    roomNumber: "G-0503",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 48,
    rentalRate: 45000,
    sell: 8200000,
    roomType: "Condo",
    phone: "095-222-3333",
    lineId: "@prop035",
    indexFbUrl: "https://facebook.com/prop035",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 92,
    distanceStation: "Ploenchit BTS",
    note: "Large 1BR with dining area",
    carPark: 0,
    messageToPost: "Large 1BR with dining area!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen", "Dining Area"],
    floor: 5,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P035-G0503",
    projectPropertyCode: "NPL003-G0503",
  },
  // Properties 36-45
  {
    id: 36,
    propertyId: 1036,
    roomNumber: "H-1607",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 65,
    rentalRate: 34000,
    sell: 6200000,
    roomType: "Condo",
    phone: "096-333-4444",
    lineId: "@prop036",
    indexFbUrl: "https://facebook.com/prop036",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 170,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Renovated 2BR with modern kitchen",
    carPark: 1,
    messageToPost: "Renovated 2BR with modern kitchen!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Kitchen", "Microwave"],
    floor: 16,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P036-H1607",
    projectPropertyCode: "LSP001-H1607",
  },
  {
    id: 37,
    propertyId: 1037,
    roomNumber: "A-0911",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 39,
    rentalRate: 24000,
    sell: 4200000,
    roomType: "Condo",
    phone: "097-444-5555",
    lineId: "@prop037",
    indexFbUrl: "https://facebook.com/prop037",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 160,
    distanceStation: "On Nut BTS",
    note: "Mid-floor 1BR with balcony garden",
    carPark: 0,
    messageToPost: "1BR with balcony garden!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Balcony"],
    floor: 9,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P037-A0911",
    projectPropertyCode: "BPE002-A0911",
  },
  {
    id: 38,
    propertyId: 1038,
    roomNumber: "B-1204",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 78,
    rentalRate: 72000,
    sell: 14800000,
    roomType: "Condo",
    phone: "098-555-6666",
    lineId: "@prop038",
    indexFbUrl: "https://facebook.com/prop038",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 82,
    distanceStation: "Ploenchit BTS",
    note: "Executive 2BR with home office space",
    carPark: 1,
    messageToPost: "Executive 2BR with home office!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Study Room",
      "Built-in Wardrobe",
    ],
    floor: 12,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P038-B1204",
    projectPropertyCode: "NPL003-B1204",
  },
  {
    id: 39,
    propertyId: 1039,
    roomNumber: "C-0812",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 37,
    rentalRate: 18500,
    sell: 3600000,
    roomType: "Condo",
    phone: "099-666-7777",
    lineId: "@prop039",
    indexFbUrl: "https://facebook.com/prop039",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 195,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Cozy 1BR perfect for young professionals",
    carPark: 0,
    messageToPost: "Cozy 1BR for young professionals!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "TV"],
    floor: 8,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: true,
    propertyCode: "P039-C0812",
    projectPropertyCode: "LSP001-C0812",
  },
  {
    id: 40,
    propertyId: 1040,
    roomNumber: "D-2013",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 58,
    rentalRate: 33000,
    sell: 5600000,
    roomType: "Condo",
    phone: "080-777-8888",
    lineId: "@prop040",
    indexFbUrl: "https://facebook.com/prop040",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 140,
    distanceStation: "On Nut BTS",
    note: "Top floor 2BR with rooftop access",
    carPark: 1,
    messageToPost: "Top floor 2BR with rooftop access!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen"],
    floor: 20,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P040-D2013",
    projectPropertyCode: "BPE002-D2013",
  },
  // Properties 41-50
  {
    id: 41,
    propertyId: 1041,
    roomNumber: "E-0605",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 52,
    rentalRate: 48000,
    sell: 8800000,
    roomType: "Condo",
    phone: "081-888-9999",
    lineId: "@prop041",
    indexFbUrl: "https://facebook.com/prop041",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 88,
    distanceStation: "Ploenchit BTS",
    note: "Oversized 1BR with walk-in closet",
    carPark: 0,
    messageToPost: "Oversized 1BR with walk-in closet!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen", "Walk-in Closet", "Dining Area"],
    floor: 6,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P041-E0605",
    projectPropertyCode: "NPL003-E0605",
  },
  {
    id: 42,
    propertyId: 1042,
    roomNumber: "F-1114",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 1,
    roomSize: 54,
    rentalRate: 26000,
    sell: 4800000,
    roomType: "Apartment",
    phone: "082-999-0000",
    lineId: "@prop042",
    indexFbUrl: "https://facebook.com/prop042",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 185,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Family-friendly 2BR apartment with playground view",
    carPark: 1,
    messageToPost: "Family 2BR apartment with playground view!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen"],
    floor: 11,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P042-F1114",
    projectPropertyCode: "LSP001-F1114",
  },
  {
    id: 43,
    propertyId: 1043,
    roomNumber: "G-1315",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "rented",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 85,
    rentalRate: 52000,
    sell: 9200000,
    roomType: "Condo",
    phone: "083-000-1111",
    lineId: "@prop043",
    indexFbUrl: "https://facebook.com/prop043",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 115,
    distanceStation: "On Nut BTS",
    note: "Luxury 3BR with master suite and guest rooms",
    carPark: 2,
    messageToPost: "Luxury 3BR with master suite!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Balcony",
      "Kitchen",
      "Master Bedroom",
      "Guest Bedroom",
      "Bathtub",
    ],
    floor: 13,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P043-G1315",
    projectPropertyCode: "BPE002-G1315",
  },
  {
    id: 44,
    propertyId: 1044,
    roomNumber: "H-0806",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 82,
    rentalRate: 78000,
    sell: 16200000,
    roomType: "Condo",
    phone: "084-111-2222",
    lineId: "@prop044",
    indexFbUrl: "https://facebook.com/prop044",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 75,
    distanceStation: "Ploenchit BTS",
    note: "Premium 2BR with panoramic city and park views",
    carPark: 1,
    messageToPost: "Premium 2BR with city and park views!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Floor-to-Ceiling Windows",
      "Marble Bathroom",
      "Walk-in Closet",
      "Balcony",
    ],
    floor: 8,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P044-H0806",
    projectPropertyCode: "NPL003-H0806",
  },
  {
    id: 45,
    propertyId: 1045,
    roomNumber: "A-1516",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 43,
    rentalRate: 22500,
    sell: 4400000,
    roomType: "Condo",
    phone: "085-222-3333",
    lineId: "@prop045",
    indexFbUrl: "https://facebook.com/prop045",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: true,
    distanceToStation: 175,
    distanceStation: "Makkasan Airport Rail Link",
    note: "High floor 1BR with airport runway views",
    carPark: 1,
    messageToPost: "High floor 1BR with runway views!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Balcony"],
    floor: 15,
    whenAvailable: "Immediately",
    isAcceptShortTerm: true,
    propertyCode: "P045-A1516",
    projectPropertyCode: "LSP001-A1516",
  },
  {
    id: 46,
    propertyId: 1046,
    roomNumber: "B-0717",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 41,
    rentalRate: 25500,
    sell: 4400000,
    roomType: "Condo",
    phone: "086-333-4444",
    lineId: "@prop046",
    indexFbUrl: "https://facebook.com/prop046",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: false,
    distanceToStation: 155,
    distanceStation: "On Nut BTS",
    note: "Modern 1BR with smart home automation",
    carPark: 0,
    messageToPost: "Modern 1BR with smart home features!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "TV", "Microwave"],
    floor: 7,
    whenAvailable: "Next month",
    isAcceptShortTerm: true,
    propertyCode: "P046-B0717",
    projectPropertyCode: "BPE002-B0717",
  },
  {
    id: 47,
    propertyId: 1047,
    roomNumber: "C-1907",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "sold",
    bedRoom: 3,
    bathRoom: 3,
    roomSize: 125,
    rentalRate: 105000,
    sell: 25000000,
    roomType: "Condo",
    phone: "087-444-5555",
    lineId: "@prop047",
    indexFbUrl: "https://facebook.com/prop047",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 60,
    distanceStation: "Ploenchit BTS",
    note: "Ultra-luxury penthouse with private pool",
    carPark: 3,
    messageToPost: "Ultra-luxury penthouse with private pool!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Floor-to-Ceiling Windows",
      "Marble Bathroom",
      "Walk-in Closet",
      "Built-in Wardrobe",
      "Kitchen",
      "Study Room",
      "Master Bedroom",
      "Guest Bedroom",
    ],
    floor: 19,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: false,
    propertyCode: "P047-C1907",
    projectPropertyCode: "NPL003-C1907",
  },
  {
    id: 48,
    propertyId: 1048,
    roomNumber: "D-1218",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 68,
    rentalRate: 36000,
    sell: 6800000,
    roomType: "Condo",
    phone: "088-555-6666",
    lineId: "@prop048",
    indexFbUrl: "https://facebook.com/prop048",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 165,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Spacious 2BR with separate work from home area",
    carPark: 1,
    messageToPost: "Spacious 2BR with work from home area!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Washing Machine", "WiFi", "TV", "Kitchen", "Study Room"],
    floor: 12,
    whenAvailable: "In 2 months",
    isAcceptShortTerm: false,
    propertyCode: "P048-D1218",
    projectPropertyCode: "LSP001-D1218",
  },
  {
    id: 49,
    propertyId: 1049,
    roomNumber: "E-1019",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 62,
    rentalRate: 35000,
    sell: 6200000,
    roomType: "Condo",
    phone: "089-666-7777",
    lineId: "@prop049",
    indexFbUrl: "https://facebook.com/prop049",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 130,
    distanceStation: "On Nut BTS",
    note: "Corner 2BR with wrap-around balcony",
    carPark: 1,
    messageToPost: "Corner 2BR with wrap-around balcony!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "Microwave", "WiFi", "Balcony", "Kitchen", "Bathtub"],
    floor: 10,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P049-E1019",
    projectPropertyCode: "BPE002-E1019",
  },
  {
    id: 50,
    propertyId: 1050,
    roomNumber: "F-2320",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 4,
    bathRoom: 4,
    roomSize: 150,
    rentalRate: 120000,
    sell: 28000000,
    roomType: "Condo",
    phone: "090-777-8888",
    lineId: "@prop050",
    indexFbUrl: "https://facebook.com/prop050",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 55,
    distanceStation: "Ploenchit BTS",
    note: "Exclusive 4BR penthouse with private terrace and city views",
    carPark: 3,
    messageToPost: "Exclusive 4BR penthouse with private terrace!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Floor-to-Ceiling Windows",
      "Marble Bathroom",
      "Walk-in Closet",
      "Built-in Wardrobe",
      "Kitchen",
      "Study Room",
      "Master Bedroom",
      "Guest Bedroom",
      "Maid's Room",
      "Storage Room",
      "Pantry",
    ],
    floor: 23,
    whenAvailable: "In 3 months",
    isAcceptShortTerm: false,
    propertyCode: "P050-F2320",
    projectPropertyCode: "NPL003-F2320",
  },
  // Properties 51-53 (final 3 properties)
  {
    id: 51,
    propertyId: 1051,
    roomNumber: "G-0421",
    projectId: 1,
    projectName: "Lumpini Suite Phetchaburi-Makkasan",
    location: ["Phetchaburi", "Makkasan", "Bangkok"],
    status: "rented",
    bedRoom: 1,
    bathRoom: 1,
    roomSize: 39,
    rentalRate: 19500,
    sell: 3900000,
    roomType: "Condo",
    phone: "091-888-9999",
    lineId: "@prop051",
    indexFbUrl: "https://facebook.com/prop051",
    imageUrls: ["/placeholder.svg?height=300&width=400"],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 190,
    distanceStation: "Makkasan Airport Rail Link",
    note: "Affordable 1BR with pool access",
    carPark: 0,
    messageToPost: "Affordable 1BR with pool access!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "TV"],
    floor: 4,
    whenAvailable: "Negotiable",
    isAcceptShortTerm: true,
    propertyCode: "P051-G0421",
    projectPropertyCode: "LSP001-G0421",
  },
  {
    id: 52,
    propertyId: 1052,
    roomNumber: "H-1622",
    projectId: 2,
    projectName: "The Base Park East Sukhumvit 77",
    location: ["Sukhumvit", "On Nut", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 1,
    roomSize: 55,
    rentalRate: 28500,
    sell: 5000000,
    roomType: "Apartment",
    phone: "092-999-0000",
    lineId: "@prop052",
    indexFbUrl: "https://facebook.com/prop052",
    imageUrls: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    isPetFriendly: true,
    isOwner: false,
    distanceToStation: 145,
    distanceStation: "On Nut BTS",
    note: "Duplex-style 2BR apartment with loft bedroom",
    carPark: 1,
    messageToPost: "Duplex 2BR apartment with loft!",
    roomAmenities: ["Air Conditioning", "Refrigerator", "WiFi", "Kitchen", "Balcony"],
    floor: 16,
    whenAvailable: "Immediately",
    isAcceptShortTerm: false,
    propertyCode: "P052-H1622",
    projectPropertyCode: "BPE002-H1622",
  },
  {
    id: 53,
    propertyId: 1053,
    roomNumber: "A-1008",
    projectId: 3,
    projectName: "Noble Ploenchit",
    location: ["Ploenchit", "Wireless Road", "Bangkok"],
    status: "available",
    bedRoom: 2,
    bathRoom: 2,
    roomSize: 88,
    rentalRate: 82000,
    sell: 17500000,
    roomType: "Condo",
    phone: "093-000-1111",
    lineId: "@prop053",
    indexFbUrl: "https://facebook.com/prop053",
    imageUrls: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    isPetFriendly: false,
    isOwner: true,
    distanceToStation: 70,
    distanceStation: "Ploenchit BTS",
    note: "Designer 2BR with custom furniture and art collection",
    carPark: 2,
    messageToPost: "Designer 2BR with custom furniture!",
    roomAmenities: [
      "Air Conditioning",
      "Refrigerator",
      "Microwave",
      "WiFi",
      "Floor-to-Ceiling Windows",
      "Marble Bathroom",
      "Walk-in Closet",
      "Built-in Wardrobe",
      "Kitchen",
      "Dining Area",
    ],
    floor: 10,
    whenAvailable: "Next month",
    isAcceptShortTerm: false,
    propertyCode: "P053-A1008",
    projectPropertyCode: "NPL003-A1008",
  },
]

const mockPropertyTypes = ["Condo", "Apartment", "Townhouse", "House"]
const mockStations = ["Makkasan Airport Rail Link", "On Nut BTS", "Phetchaburi MRT", "Sukhumvit BTS", "Ploenchit BTS"]
const mockRoomAmenities = [
  "Air Conditioning",
  "Refrigerator",
  "Washing Machine",
  "WiFi",
  "TV",
  "Microwave",
  "Balcony",
  "Bathtub",
  "Shower",
  "Kitchen",
  "Walk-in Closet",
  "Built-in Wardrobe",
]
const mockWhenAvailableOptions = ["Immediately", "Next month", "In 2 months", "In 3 months", "Negotiable"]

export function PropertyProvider({ children }: { children: ReactNode }) {
  const [properties, setProperties] = useState<Property[]>([])
  const [projects] = useState<Project[]>(mockProjects)
  const [propertyTypes] = useState<string[]>(mockPropertyTypes)
  const [stations] = useState<string[]>(mockStations)
  const [roomAmenitiesOptions] = useState<string[]>(mockRoomAmenities)
  const [whenAvailableOptions] = useState<string[]>(mockWhenAvailableOptions)
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)

  const fetchProperties = useCallback(async (page: number, limit: number, params: SearchParams) => {
    setLoading(true)
    setError(null)

    // Simulate API delay
    // await new Promise((resolve) => setTimeout(resolve, 500))
    // try {
    //   const response = await fetch(`/api/search-properties?${params.toString()}`);
    //   if (!response.ok) {
    //     throw new Error('Failed to fetch data');
    //   }
    //   const data = await response.json();
    //   setSearchResults(data.results);
    // } catch (error) {
    //   console.error('Search failed:', error);
    //   setSearchResults([]);
    // } finally {
    //   setIsLoading(false);
    // }
    try {
      const response = await fetch(`/api/properties?${params.toString()}`);

      let filteredProperties = [...mockProperties]

      // Apply filters
      if (params.search) {
        const searchLower = params.search.toLowerCase()
        filteredProperties = filteredProperties.filter(
          (property) =>
            property.projectName.toLowerCase().includes(searchLower) ||
            property.location.some((loc) => loc.toLowerCase().includes(searchLower)),
        )
      }

      if (params.roomType !== "all") {
        filteredProperties = filteredProperties.filter((property) => property.roomType === params.roomType)
      }

      if (params.bedRoom !== "all") {
        filteredProperties = filteredProperties.filter(
          (property) => property.bedRoom === Number.parseInt(params.bedRoom),
        )
      }

      if (params.minSize) {
        filteredProperties = filteredProperties.filter(
          (property) => property.roomSize >= Number.parseInt(params.minSize),
        )
      }

      if (params.maxSize) {
        filteredProperties = filteredProperties.filter(
          (property) => property.roomSize <= Number.parseInt(params.maxSize),
        )
      }

      if (params.minPrice) {
        filteredProperties = filteredProperties.filter(
          (property) => property.rentalRate >= Number.parseInt(params.minPrice),
        )
      }

      if (params.maxPrice) {
        filteredProperties = filteredProperties.filter(
          (property) => property.rentalRate <= Number.parseInt(params.maxPrice),
        )
      }

      // Pagination
      const total = filteredProperties.length
      const totalPages = Math.ceil(total / limit)
      const startIndex = (page - 1) * limit
      const endIndex = startIndex + limit
      const paginatedProperties = filteredProperties.slice(startIndex, endIndex)

      setProperties(paginatedProperties)
      setLoading(false)

      return {
        success: true,
        total,
        page,
        totalPages,
      }
    } catch (err) {
      setError("Failed to fetch properties")
      setLoading(false)
      return {
        success: false,
        total: 0,
        page: 1,
        totalPages: 0,
      }
    }
  }, [])

  const getProperty = useCallback(async (id: number) => {
    setLoading(true)
    setError(null)

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 300))

    try {
      const property = mockProperties.find((p) => p.id === id)
      if (property) {
        setLoading(false)
        return { success: true, data: property }
      } else {
        setError("Property not found")
        setLoading(false)
        return { success: false }
      }
    } catch (err) {
      setError("Failed to fetch property")
      setLoading(false)
      return { success: false }
    }
  }, [])

  const updateProperty = useCallback(async (id: number, data: Partial<Property>) => {
    setSaving(true)
    setError(null)
    setSuccessMessage(null)

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000))

    try {
      // In a real app, this would make an API call
      // For now, we'll just simulate success
      setSuccessMessage("Property updated successfully!")
      setSaving(false)
      return { success: true, message: "Property updated successfully!" }
    } catch (err) {
      setError("Failed to update property")
      setSaving(false)
      return { success: false }
    }
  }, [])

  const clearError = useCallback(() => {
    setError(null)
  }, [])

  const clearSuccessMessage = useCallback(() => {
    setSuccessMessage(null)
  }, [])

  const value: PropertyContextType = {
    properties,
    projects,
    propertyTypes,
    stations,
    roomAmenitiesOptions,
    whenAvailableOptions,
    loading,
    saving,
    error,
    successMessage,
    fetchProperties,
    getProperty,
    updateProperty,
    clearError,
    clearSuccessMessage,
  }

  return <PropertyContext.Provider value={value}>{children}</PropertyContext.Provider>
}

export function useProperty() {
  const context = useContext(PropertyContext)
  if (context === undefined) {
    throw new Error("useProperty must be used within a PropertyProvider")
  }
  return context
}
